package orm_generator

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
)

// Helper function to check if a file or directory exists
func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func TestNewCodeGenerator(t *testing.T) {
	config := GenerationConfig{
		PackageName:  "test",
		OutputDir:    "/tmp/test",
		Models:       []string{"User", "Post"},
		Features:     []string{"columns", "repositories"},
		IncludeTests: true,
		IncludeDocs:  true,
	}

	generator := NewCodeGenerator(config)

	assert.NotNil(t, generator)
	assert.Equal(t, "test", generator.packageName)
	assert.Equal(t, "/tmp/test", generator.outputDir)
	assert.NotNil(t, generator.tagParser)
	assert.NotNil(t, generator.templates)
	assert.NotNil(t, generator.models)
}

func TestCodeGenerator_GenerateCode(t *testing.T) {
	tmpDir := os.TempDir()
	outputDir := filepath.Join(tmpDir, "orm_generator_test")
	defer os.RemoveAll(outputDir)

	config := GenerationConfig{
		PackageName:  "testmodels",
		OutputDir:    outputDir,
		Models:       []string{},
		Features:     []string{"columns", "repositories"},
		IncludeTests: false,
		IncludeDocs:  false,
	}

	generator := NewCodeGenerator(config)

	testModel := &ModelMetadata{
		Name:    "TestUser",
		Package: "testmodels",
		Fields: []FieldMetadata{
			{
				Name:            "ID",
				Type:            "int",
				DBName:          "id",
				IsPrimaryKey:    true,
				IsAutoGenerated: true,
			},
			{
				Name:   "Name",
				Type:   "string",
				DBName: "name",
			},
		},
		Relationships: []FieldMetadata{},
	}

	generator.models["TestUser"] = testModel

	err := generator.GenerateAll()
	if err != nil {
		t.Logf("GenerateAll failed: %v", err)

	}

	assert.DirExists(t, outputDir)
}

func TestCodeGenerator_GetModel(t *testing.T) {
	config := GenerationConfig{
		PackageName: "test",
		OutputDir:   "/tmp/test",
	}

	generator := NewCodeGenerator(config)

	model := &ModelMetadata{
		Name:    "TestModel",
		Package: "test",
		Fields: []FieldMetadata{
			{
				Name:         "ID",
				Type:         "int",
				DBName:       "id",
				IsPrimaryKey: true,
			},
		},
	}

	generator.models["TestModel"] = model

	retrievedModel, exists := generator.GetModel("TestModel")
	assert.True(t, exists)
	assert.Equal(t, model, retrievedModel)

	_, exists = generator.GetModel("NonExistent")
	assert.False(t, exists)
}

func TestCodeGenerator_GetModelNames(t *testing.T) {
	config := GenerationConfig{
		PackageName: "test",
		OutputDir:   "/tmp/test",
	}

	generator := NewCodeGenerator(config)

	model1 := &ModelMetadata{Name: "Model1", Package: "test"}
	model2 := &ModelMetadata{Name: "Model2", Package: "test"}

	generator.models["Model1"] = model1
	generator.models["Model2"] = model2

	names := generator.GetModelNames()
	assert.Len(t, names, 2)
	assert.Contains(t, names, "Model1")
	assert.Contains(t, names, "Model2")
}

func TestValidateModels(t *testing.T) {
	config := GenerationConfig{
		PackageName: "test",
		OutputDir:   "/tmp/test",
	}

	generator := NewCodeGenerator(config)

	model := &ModelMetadata{
		Name:    "TestModel",
		Package: "test",
		Fields: []FieldMetadata{
			{
				Name:         "ID",
				Type:         "int",
				DBName:       "id",
				IsPrimaryKey: true,
			},
			{
				Name:   "Name",
				Type:   "string",
				DBName: "name",
			},
		},
	}

	generator.models["TestModel"] = model

	err := generator.ValidateModels()
	if err != nil {
		t.Logf("ValidateModels failed: %v", err)

	}
}

func TestGenerateForModel(t *testing.T) {
	tmpDir := os.TempDir()
	outputDir := filepath.Join(tmpDir, "model_generate_test")
	defer os.RemoveAll(outputDir)

	config := GenerationConfig{
		PackageName: "test",
		OutputDir:   outputDir,
	}

	generator := NewCodeGenerator(config)

	model := &ModelMetadata{
		Name:    "TestModel",
		Package: "test",
		Fields: []FieldMetadata{
			{
				Name:         "ID",
				Type:         "int",
				DBName:       "id",
				IsPrimaryKey: true,
			},
		},
	}

	generator.models["TestModel"] = model

	err := generator.GenerateForModel("TestModel")
	if err != nil {
		t.Logf("GenerateForModel failed: %v", err)

	}

	t.Logf("GenerateForModel completed, output directory exists: %v", fileExists(outputDir))
}
